db:
  image: postgres

web:
  image: webgoal/teias-de-aprendizagem
  restart: always
  command: bundle exec unicorn_rails -c config/unicorn.rb
  volumes:
    - /tmp:/tmp
  links:
    - db
    - nginx

nginx:
  build: ./nginx/prod
  volumes:
    - /tmp:/tmp
  ports:
    - 80:80
